// @ts-check
import { readFile, writeFile, rename } from 'node:fs/promises';
import { build } from 'tsup';

console.log('Building script-bridge-client...');

const packageJson = JSON.parse(await readFile('package.json', 'utf8'));
const header = `// AUTOGENERATED FILE. DO NOT EDIT.
//
// @script-bridge/client@${packageJson.version}
// author: ${packageJson.author}
// license: ${packageJson.license}
// repository: ${packageJson.homepage}
//`;

await build({
  entryPoints: ['src/index.ts'],
  outDir: 'build',
  target: 'es2021',
  platform: 'neutral',
  format: 'esm',
  external: ['@minecraft/server', '@minecraft/server-net'],
  noExternal: ['@script-bridge/protocol'],
  bundle: true,
  minify: true,
  dts: true,
  banner: {
    js: header
  }
});

await rename('build/index.mjs', 'build/script-bridge-client.js');
await rename('build/index.d.mts', 'build/script-bridge-client.d.ts');

await writeFile(
  'build/script-bridge-client.d.ts',
  header + '\n' + (await readFile('build/script-bridge-client.d.ts', 'utf8'))
);

console.log('Build complete');