import { readFile, writeFile, rename } from 'node:fs/promises';
import * as esbuild from 'esbuild';
import dtsPlugin from 'esbuild-plugin-d.ts';

console.log('Building script-bridge-client...');

const packageJson = JSON.parse(await readFile('package.json', 'utf8'));
const header = `// AUTOGENERATED FILE. DO NOT EDIT.
//
// @script-bridge/client@${packageJson.version}
// author: ${packageJson.author}
// license: ${packageJson.license}
// repository: ${packageJson.homepage}
//`;

await esbuild.build({
  entryPoints: ['src/index.ts'],
  outfile: 'build/script-bridge-client.js',
  target: 'es2021',
  charset: 'utf8',
  platform: 'neutral',
  external: ['@minecraft/server', '@minecraft/server-net'],
  bundle: true,
  minify: true,
  plugins: [
    dtsPlugin({
      experimentalBundling: true
    })
  ],
  banner: {
    js: header
  }
});

await rename('build/index.d.ts', 'build/script-bridge-client.d.ts');

await writeFile(
  'build/script-bridge-client.d.ts',
  header + '\n' + (await readFile('build/script-bridge-client.d.ts', 'utf8'))
);

console.log('Build complete');
