name: Release Package

on:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  id-token: write # Required for OIDC

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - name: Update npm
        run: |
          npm install -g npm@latest
          npm --version

      - name: Read package version
        id: version
        run: |
          release_version=$(git describe --tags --abbrev=0)
          package_version=$(node -p -e "require('./package.json').version")
          if [ "$release_version" != "v$package_version" ]; then
            echo "Error: Release version $release_version does not match package version $package_version"
            exit 1
          fi
          echo "version=$package_version" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: pnpm install

      - name: "[protocol] Build and Publish"
        run: |
          cd protocol
          pnpm publish --no-git-checks --access public
      - name: "[server] Build and Publish"
        run: |
          cd server
          pnpm publish --no-git-checks --access public

      - name: "[client] Build and Publish"
        run: |
          cd client
          pnpm publish --no-git-checks --access public

      - name: "[client] Bundle"
        run: |
          cd client
          pnpm run bundle
          zip script-bridge-client-v${{ steps.version.outputs.version }}.zip -j build/script-bridge-client.js build/script-bridge-client.d.ts

      - name: "[client] Upload Release Asset (ZIP)"
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: client/script-bridge-client-v${{ steps.version.outputs.version }}.zip
          asset_name: script-bridge-client-v${{ steps.version.outputs.version }}.zip
          asset_content_type: application/zip
          
      - name: "[client] Upload Release Asset (DTS)"
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: client/build/script-bridge-client.d.ts
          asset_name: script-bridge-client.d.ts
          asset_content_type: application/typescript
              
      - name: "[client] Upload Release Asset (JS)"
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: client/build/script-bridge-client.js
          asset_name: script-bridge-client.js
          asset_content_type: application/javascript